blobstore feature. [Finishes #146714671]
c0-ops/ert-concourse pull request #4
Opened 2017-06-23 20:45 UTC by mxplusb

Finishes the blobstore delivery story. Squashed a long commit history for brevity.

Signed-off-by: Mike Lloyd <kevin.michael.lloyd@gmail.com>

//cc @sreenivasmrpivot

2017-06-26 16:27 UTC, krishicks requested changes

2017-06-26 16:27 UTC, krishicks commented on ci/tasks/configure-ert.sh
> +  --arg azure_resources_container ${azure_resources_container} \
These args should all be wrapped in quotes; parameter expansion (`${}`) would mean anyone using spaces in the variable names would get unexpected args.

2017-06-26 16:27 UTC, krishicks commented on json_templates/azure/c0-azure-base/ert-template.json
> +          "name": "null"
I see this was null before; why null?

2017-06-26 16:27 UTC, krishicks commented on json_templates/azure/c0-azure-base/ert-template.json
> +        "value": "c0-coreteam@pivotal.io"
This should be a param for the pipeline, not defaulted to c0-coreteam@pivotal.io.

2017-06-26 16:27 UTC, krishicks commented on json_templates/azure/c0-azure-base/ert-template.json
> +    "consul_server": {
Is this just a formatting change or have the values also changed?

2017-06-27 21:11 UTC, sreenivasmrpivot commented on json_templates/azure/c0-azure-base/ert-template.json
> +          "name": "null"
@krishicks not sure why it was null. We can create a new bug or story in the tracker to get to this. The scope of this story was just to support the azure blob store for ERT tile.

2017-06-27 21:12 UTC, sreenivasmrpivot commented on json_templates/azure/c0-azure-base/ert-template.json
> +        "value": "c0-coreteam@pivotal.io"
@krishicks This is a pre-existing code we can create a new bug or story in the tracker to get to this. The scope of this story was just to support the azure blob store for ERT tile.

2017-06-27 22:29 UTC, sreenivasmrpivot commented on json_templates/azure/c0-azure-base/ert-template.json
> +    "consul_server": {
@krishicks i have verified it using BeyondCompare text compare. It seems to be just formatting which has changed. there is no change in the text though.

2017-06-28 16:41 UTC, merged

2017-06-29 18:57 UTC, abbyachau commented on json_templates/azure/c0-azure-base/ert-template.json
> +        "value": "c0-coreteam@pivotal.io"
Created a tracker story for this: #148097385.